#ifndef MATHENUM_INCLUDED
#define MATHENUM_INCLUDED

enum ENUM_MATH_INCREMENT_METHOD_TYPE
{
  MATH_INCREMENT_METHOD_TYPE_ADD,      //[00] Adição (+)
  MATH_INCREMENT_METHOD_TYPE_MULTIPLY, //[01] Multiplicação (*)
  MATH_INCREMENT_METHOD_TYPE_REMOVE,   //[02] Subtração (-)
  MATH_INCREMENT_METHOD_TYPE_DIVIDE,   //[03] Divisão (/)
  MATH_INCREMENT_METHOD_TYPE_DEFINE    //[04] Definição (=)
};

#endif /* MATHENUM_INCLUDED */
